title: Daniel Bowden
#Your site's domain goes here. Leave localhost server or blank when working locally.
#url: http://0.0.0.0:4000
url: https://www.danielbowden.com.au

owner:
  name: Daniel Bowden
  avatar: avatar.jpg
  avatar-banner: avatar-banner.jpg
  bio: "Software Engineering Lead based in Sydney, Australia. Specialising in mobile development and interested in exposure to exciting new technologies, innovative ideas, automation, quality engineering, DevOps and the opportunity to experiment and learn new things everyday."
  about: "Software Engineering Lead based in Sydney, Australia"
  details: "Specialising in mobile development and interested in exposure to exciting new technologies, innovative ideas, software engineering, automation, quality, DevOps and the opportunity to experiment and learn new things everyday."
  email: daniel@bowden.in
  twitter: https://twitter.com/danielgbowden
  twitter-handle: "@danielgbowden"
  github: https://github.com/danielbowden
  stackexchange: http://careers.stackoverflow.com/danielbowden
  linkedin: http://www.linkedin.com/in/danielgbowden

google_analytics: UA-52578678-1
google_verify: XRYjfggmrG1zd8QJvZN3lLbnYGyn5HrRM_oNFPiOvew

timezone: Australia/Sydney
future: true
permalink: pretty
markdown: kramdown
sass:
  sass_dir: assets/styles

mapping:
  provider: google_js
  api_key: AIzaSyA-YoSaEBJVaSSxzLDLyycbt24kAttfyhU
  zoom: 0

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "tmp", "*.sublime-project", "*.sublime-workspace"]
