title: Daniel Bowden
#Your site's domain goes here. Leave localhost server or blank when working locally.
#url: http://0.0.0.0:4000
url: http://www.danielbowden.com.au

owner:
  name: Daniel Bowden
  avatar: avatar.jpg
  bio: "Software engineer based in Sydney, Australia. Specialising in mobile development and interested in exposure to exciting new technologies, innovative ideas, social interactivity and the opportunity to experiment and learn new things everyday."
  email: daniel@bowden.in
  twitter: https://twitter.com/danielgbowden      
  github: https://github.com/danielbowden
  stackexchange: http://careers.stackoverflow.com/danielbowden
  linkedin: http://www.linkedin.com/in/danielgbowden

timezone: Australia/Sydney
future: true
pygments: true
markdown: kramdown

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "tmp", "*.sublime-project", "*.sublime-workspace"]
